"""adding amount to custompodcast

Revision ID: 0ae427ecaaca
Revises: 50c9915476fa
Create Date: 2024-08-04 23:35:29.550166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ae427ecaaca'
down_revision: Union[str, None] = '50c9915476fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custompodcast', sa.Column(
        'amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custompodcast', 'amount')
    # ### end Alembic commands ###
