name: Docker Image Publish

on:
    workflow_run:
        workflows: ["Run Tests"]
        branches: ["prod"]
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: "prod"
            - name: Set up QEMU for ARM64
              run: |
                  sudo apt-get update
                  sudo apt-get install -y qemu-system-modules-spice binfmt-support qemu-user-static
                  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            - name: build image
              run: docker build -t pilix/podshiftapi:arm64 --target prod --platform linux/arm64 .
            - name: push
              run: |
                  docker login -u pilix -p ${{ secrets.DOCKER_HUB_TOKEN }}
                  docker push pilix/podshiftapi:arm64
